name: Pull request workflow

on:
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  lint:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8

      - name: Run linter
        run: ./gradlew --parallel lint
  unit_tests:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8

      - name: Unit tests
        run: ./gradlew --parallel test