name: Pull Request

on:
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Check Out
        uses: actions/checkout@v2

      - name: Set Up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Build
        run: ./gradlew build